#!/bin/sh

. ./code/box_lib.sh

setup() {
  groupadd databox
  useradd blueox 
  mkdir /jails
  mkdir -p /opt/basejail/etc
  create_user_directories blueox
  furnish_box blueox
}

runtests() {
  assert '/home/blueox exists' [ -e /home/blueox ]
  assert '/home/blueox/http exists' [ -e /home/blueox/http ]
  assert '/jails/blueox/ exists' [ -e /jails/blueox/ ]
  assert 'root owns /jails/blueox' [ "`ls -dl /jails/blueox| cut -d \  -f 3`" = 'root' ]
  assert 'blueox owns /home/blueox/' [ "`ls -dl /home/blueox/| cut -d \  -f 3`" = 'blueox' ]

  assert "/opt/basejail/etc/passwd contains blueox" [ $(grep blueox /opt/basejail/etc/passwd) ]


}

teardown() {
  userdel blueox
  groupdel databox
  rm -R /home/blueox
  rm -R /jails
  rm -R /opt/basejail
}

