#!/bin/sh
# run me with . activate

OLD_PATH=$PATH
OLD_PS1=$PS1
OLD_NODE_PATH=$NODE_PATH
PATH=$(pwd)/node_modules/.bin:$(pwd)/bin:$PATH

# Add ./code to NODE_PATH, adding a separating ':' if NODE_PATH
# is already set.
# See http://pubs.opengroup.org/onlinepubs/009695399/utilities/xcu_chap02.html#tag_02_06_02
export NODE_PATH=$(pwd)/code${NODE_PATH+:}${NODE_PATH}

if [ -z "$COBALT_PORT" ]
then
  export COBALT_PORT=3000
fi

PS1="[co]$PS1"
deactivate () {
    PATH=$OLD_PATH
    PS1=$OLD_PS1
    NODE_PATH=$OLD_NODE_PATH
    unset -f deactivate
}

mocha () {
    # Clean DB out and load fixtures
    coffee cleaner.coffee
    #mongofixtures cu-test fixtures.js
    # Consider pushing to external program.
    eval last=\${$#}

    if [ "$#" = "0" ]
    then
        env mocha ${@:1:$#-1} $(find test -name '*.coffee' | sort)
    else
        if [ -d "$last" ]
        then
            env mocha ${@:1:$#-1} $(find "$last" -name '*.coffee' | sort)
        else
            env mocha $@
        fi
    fi
}

s=../swops-secret/keys.sh
test -e "$s" && . "$s"
true
